### Basics

In [18]:
import torch

In [3]:
x = torch.empty(2,2,3) # creating a tensor 2 dimentional, 2 x 3 
x

tensor([[[6.7061e+22, 2.1590e-04, 6.7441e-10],
         [8.2649e+20, 2.6880e-06, 2.1159e-07]],

        [[1.3002e+22, 6.7134e-07, 1.0616e+21],
         [3.4332e-06, 4.2467e+21, 2.1180e+23]]])

In [4]:
# check size
print(x.size())

# check data type
print(x.dtype)

# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2, 2, 3])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16
torch.Size([2])


In [5]:
# List to tensor
my_list = [2,4,5,7]
t = torch.tensor(my_list)
t

tensor([2, 4, 5, 7])

In [6]:
# Operations

u = torch.rand(2,2)
o = torch.rand(2,2)
u.add_(o) # in place operation, every operation ends with _ is in place.
print(u)
#print(o)
l_1 = u + o  #elementwise edition
print(l_1)
l_2 = torch.add(u,o)
print(l_2)
torch.mul(u,o)
u.mul_(o) # in place operation, every function with _, in place. 

tensor([[1.5403, 1.0998],
        [1.7716, 0.6487]])
tensor([[2.2989, 1.3601],
        [2.6520, 0.8981]])
tensor([[2.2989, 1.3601],
        [2.6520, 0.8981]])


tensor([[1.1685, 0.2862],
        [1.5597, 0.1618]])

In [8]:
# Create 5 x 3 tensor
x = torch.rand(5 ,3)
print(x)
# slicing, get all rows but one cols 
print(x[:,0])
print(x[1,:]) # second row and all cols 

tensor([[0.2281, 0.4573, 0.9780],
        [0.7050, 0.0919, 0.7054],
        [0.8904, 0.4137, 0.0152],
        [0.8018, 0.0813, 0.1779],
        [0.9780, 0.0605, 0.8127]])
tensor([0.2281, 0.7050, 0.8904, 0.8018, 0.9780])
tensor([0.7050, 0.0919, 0.7054])


In [9]:
print(x[1,1].item()) # gets the exact value if you have one element in your tensor. 
 # without the item() function the return value is a tensor. 

0.09192723035812378


In [10]:
# reshaping 
x = torch.rand(4,4)
print(x)
y = x.view(16) # 1 d vector 
print(y)
k = x.view(-1,8) # -1 to determine the size, torch takes care of this thing. 
print(k.size())

tensor([[0.4263, 0.2436, 0.2479, 0.2989],
        [0.1207, 0.7850, 0.3067, 0.5707],
        [0.0121, 0.9760, 0.1458, 0.8329],
        [0.2884, 0.9296, 0.1506, 0.3856]])
tensor([0.4263, 0.2436, 0.2479, 0.2989, 0.1207, 0.7850, 0.3067, 0.5707, 0.0121,
        0.9760, 0.1458, 0.8329, 0.2884, 0.9296, 0.1506, 0.3856])
torch.Size([2, 8])


In [11]:
# converting from a torch to numpy tensor vs. 
import numpy as np 

# create a tensor, be careful if you are on a cpu not a gpu both objects with share the same memory,
# so changing one will change the other. 
a = torch.ones(5)
print(a)
b = a.numpy()
#print(type(b))
a.add_(1) # add one to each element, notice the b will change as well. 
#print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[2. 2. 2. 2. 2.]


In [12]:
# be careful! 
a = np.ones(5)
b = torch.from_numpy(a)
#print(b)

a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [15]:
# check if cuda available 

if torch.cuda.is_available():
    device = torch.device('cuda')
    print(True)
else:
    device = torch.device('cpu')
    print(False)

False


In [16]:
m = torch.ones(5, device=device) # create and put the tensor on the gpu 
# or create the tensor then move to the gpu
v = torch.ones(5)
v = v.to(device)
# if we do addition operation will be handled on gpu
# z = m + v 
# numpy handles only cpu tensors. 

In [17]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()